module.exports = {
	lists: [
		['numeric', 'feather', 'military', 'average', 'president', 'pistol', 'ray', 'complete', 'escape', 'monarchy'],
		['numeral', 'feather', 'military', 'average', 'president', 'pistol', 'ray', 'complete', 'escape', 'monarchy'],
		['numeral', 'plume', 'military', 'average', 'president', 'pistol', 'ray', 'complete', 'escape', 'monarchy'],
		['numeral', 'plume', 'army', 'average', 'president', 'pistol', 'ray', 'complete', 'escape', 'monarchy'],
		['numeral', 'plume', 'army', 'ordinary', 'president', 'pistol', 'ray', 'complete', 'escape', 'monarchy'],
		['numeral', 'plume', 'army', 'ordinary', 'leader', 'pistol', 'ray', 'complete', 'escape', 'monarchy'],
		['numeral', 'plume', 'army', 'ordinary', 'leader', 'gun', 'ray', 'complete', 'escape', 'monarchy'],
		['numeral', 'plume', 'army', 'ordinary', 'leader', 'gun', 'bar', 'complete', 'escape', 'monarchy'],
		['numeral', 'plume', 'army', 'ordinary', 'leader', 'gun', 'bar', 'achieve', 'escape', 'monarchy'],
		['numeral', 'plume', 'army', 'ordinary', 'leader', 'gun', 'bar', 'achieve', 'breakout', 'monarchy'],
		['numeral', 'plume', 'army', 'ordinary', 'leader', 'gun', 'bar', 'achieve', 'breakout', 'sovereignty'],
	],
	words: {
		achieve: [8, 9, 10],
		army: [3, 4, 5, 6, 7, 8, 9, 10],
		average: [0, 1, 2, 3],
		bar: [7, 8, 9, 10],
		breakout: [9, 10],
		complete: [0, 1, 2, 3, 4, 5, 6, 7],
		escape: [0, 1, 2, 3, 4, 5, 6, 7, 8],
		feather: [0, 1],
		gun: [6, 7, 8, 9, 10],
		leader: [5, 6, 7, 8, 9, 10],
		military: [0, 1, 2],
		monarchy: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
		numeral: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		numeric: [0],
		ordinary: [4, 5, 6, 7, 8, 9, 10],
		pistol: [0, 1, 2, 3, 4, 5],
		plume: [2, 3, 4, 5, 6, 7, 8, 9, 10],
		president: [0, 1, 2, 3, 4],
		ray: [0, 1, 2, 3, 4, 5, 6],
		sovereignty: [10],
		unused: []
	}
};
